# Generated by Django 2.2.16 on 2022-05-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220513_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TitlesGenres',
            new_name='GenreTitle',
        ),
    ]
